- name: Pre-install for Graylog
  apt:
    name: [apt-transport-https, uuid-runtime]
    state: latest

- name: Install Graylog
  apt:
    deb: "{{graylog_deb_url}}"
    state: latest
    update_cache: yes

- name: Install Graylog-Server
  apt:
    name: graylog-server
    state: latest
    update_cache: yes

- name: Install Graylog Integrations Plugins or the Enterprise Plugins
  apt:
    name: [graylog-enterprise-plugins, graylog-integrations-plugins, graylog-enterprise-integrations-plugins]
    state: latest
    update_cache: yes
